ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of MSSM_SLHA2'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_246 = ', GC_246
      WRITE(*,2) 'GC_250 = ', GC_250
      WRITE(*,2) 'GC_311 = ', GC_311
